<?php
/**
 * CartCartItem
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CartCartItem Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CartCartItem implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    protected static $withAdditionalProperties = false;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'cartCartItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'product_grn' => 'string',
        'product_configuration' => '\OpenAPI\Client\Model\CartProductConfigurationStep[]',
        'quantity' => 'int',
        'price' => '\OpenAPI\Client\Model\CartMoney',
        'list_price' => '\OpenAPI\Client\Model\CartMoney',
        'discount' => '\OpenAPI\Client\Model\CartMoney',
        'base_price' => '\OpenAPI\Client\Model\CartMoney',
        'custom_price' => '\OpenAPI\Client\Model\CartItemCustomPrice',
        'vat_amount' => '\OpenAPI\Client\Model\CartMoney',
        'vat_percentage' => 'float',
        'vat_inaccurate' => 'bool',
        'vat_calculated' => 'bool',
        'localized_name' => 'array<string,string>',
        'product_code' => 'string',
        'product_sku' => 'string',
        'image_grn' => 'string',
        'variant_options' => 'string',
        'is_virtual' => 'bool',
        'promotion_grns' => 'string[]',
        'additional_info' => 'string',
        'product_data' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'product_grn' => null,
        'product_configuration' => null,
        'quantity' => 'int64',
        'price' => null,
        'list_price' => null,
        'discount' => null,
        'base_price' => null,
        'custom_price' => null,
        'vat_amount' => null,
        'vat_percentage' => 'float',
        'vat_inaccurate' => null,
        'vat_calculated' => null,
        'localized_name' => null,
        'product_code' => null,
        'product_sku' => null,
        'image_grn' => null,
        'variant_options' => null,
        'is_virtual' => null,
        'promotion_grns' => null,
        'additional_info' => null,
        'product_data' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'product_grn' => false,
        'product_configuration' => false,
        'quantity' => false,
        'price' => false,
        'list_price' => false,
        'discount' => false,
        'base_price' => false,
        'custom_price' => false,
        'vat_amount' => false,
        'vat_percentage' => false,
        'vat_inaccurate' => false,
        'vat_calculated' => false,
        'localized_name' => false,
        'product_code' => false,
        'product_sku' => false,
        'image_grn' => false,
        'variant_options' => false,
        'is_virtual' => false,
        'promotion_grns' => false,
        'additional_info' => false,
        'product_data' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'product_grn' => 'productGrn',
        'product_configuration' => 'productConfiguration',
        'quantity' => 'quantity',
        'price' => 'price',
        'list_price' => 'listPrice',
        'discount' => 'discount',
        'base_price' => 'basePrice',
        'custom_price' => 'customPrice',
        'vat_amount' => 'vatAmount',
        'vat_percentage' => 'vatPercentage',
        'vat_inaccurate' => 'vatInaccurate',
        'vat_calculated' => 'vatCalculated',
        'localized_name' => 'localizedName',
        'product_code' => 'productCode',
        'product_sku' => 'productSku',
        'image_grn' => 'imageGrn',
        'variant_options' => 'variantOptions',
        'is_virtual' => 'isVirtual',
        'promotion_grns' => 'promotionGrns',
        'additional_info' => 'additionalInfo',
        'product_data' => 'productData'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'product_grn' => 'setProductGrn',
        'product_configuration' => 'setProductConfiguration',
        'quantity' => 'setQuantity',
        'price' => 'setPrice',
        'list_price' => 'setListPrice',
        'discount' => 'setDiscount',
        'base_price' => 'setBasePrice',
        'custom_price' => 'setCustomPrice',
        'vat_amount' => 'setVatAmount',
        'vat_percentage' => 'setVatPercentage',
        'vat_inaccurate' => 'setVatInaccurate',
        'vat_calculated' => 'setVatCalculated',
        'localized_name' => 'setLocalizedName',
        'product_code' => 'setProductCode',
        'product_sku' => 'setProductSku',
        'image_grn' => 'setImageGrn',
        'variant_options' => 'setVariantOptions',
        'is_virtual' => 'setIsVirtual',
        'promotion_grns' => 'setPromotionGrns',
        'additional_info' => 'setAdditionalInfo',
        'product_data' => 'setProductData'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'product_grn' => 'getProductGrn',
        'product_configuration' => 'getProductConfiguration',
        'quantity' => 'getQuantity',
        'price' => 'getPrice',
        'list_price' => 'getListPrice',
        'discount' => 'getDiscount',
        'base_price' => 'getBasePrice',
        'custom_price' => 'getCustomPrice',
        'vat_amount' => 'getVatAmount',
        'vat_percentage' => 'getVatPercentage',
        'vat_inaccurate' => 'getVatInaccurate',
        'vat_calculated' => 'getVatCalculated',
        'localized_name' => 'getLocalizedName',
        'product_code' => 'getProductCode',
        'product_sku' => 'getProductSku',
        'image_grn' => 'getImageGrn',
        'variant_options' => 'getVariantOptions',
        'is_virtual' => 'getIsVirtual',
        'promotion_grns' => 'getPromotionGrns',
        'additional_info' => 'getAdditionalInfo',
        'product_data' => 'getProductData'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Associative array for storing additional properties
     *
     * @var mixed[]
     */
    protected $additionalProperties = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('product_grn', $data ?? [], null);
        $this->setIfExists('product_configuration', $data ?? [], null);
        $this->setIfExists('quantity', $data ?? [], null);
        $this->setIfExists('price', $data ?? [], null);
        $this->setIfExists('list_price', $data ?? [], null);
        $this->setIfExists('discount', $data ?? [], null);
        $this->setIfExists('base_price', $data ?? [], null);
        $this->setIfExists('custom_price', $data ?? [], null);
        $this->setIfExists('vat_amount', $data ?? [], null);
        $this->setIfExists('vat_percentage', $data ?? [], null);
        $this->setIfExists('vat_inaccurate', $data ?? [], null);
        $this->setIfExists('vat_calculated', $data ?? [], null);
        $this->setIfExists('localized_name', $data ?? [], null);
        $this->setIfExists('product_code', $data ?? [], null);
        $this->setIfExists('product_sku', $data ?? [], null);
        $this->setIfExists('image_grn', $data ?? [], null);
        $this->setIfExists('variant_options', $data ?? [], null);
        $this->setIfExists('is_virtual', $data ?? [], null);
        $this->setIfExists('promotion_grns', $data ?? [], null);
        $this->setIfExists('additional_info', $data ?? [], null);
        $this->setIfExists('product_data', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets product_grn
     *
     * @return string|null
     */
    public function getProductGrn()
    {
        return $this->container['product_grn'];
    }

    /**
     * Sets product_grn
     *
     * @param string|null $product_grn product_grn
     *
     * @return self
     */
    public function setProductGrn($product_grn)
    {
        if (is_null($product_grn)) {
            throw new \InvalidArgumentException('non-nullable product_grn cannot be null');
        }
        $this->container['product_grn'] = $product_grn;

        return $this;
    }

    /**
     * Gets product_configuration
     *
     * @return \OpenAPI\Client\Model\CartProductConfigurationStep[]|null
     */
    public function getProductConfiguration()
    {
        return $this->container['product_configuration'];
    }

    /**
     * Sets product_configuration
     *
     * @param \OpenAPI\Client\Model\CartProductConfigurationStep[]|null $product_configuration product_configuration
     *
     * @return self
     */
    public function setProductConfiguration($product_configuration)
    {
        if (is_null($product_configuration)) {
            throw new \InvalidArgumentException('non-nullable product_configuration cannot be null');
        }
        $this->container['product_configuration'] = $product_configuration;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return int|null
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param int|null $quantity quantity
     *
     * @return self
     */
    public function setQuantity($quantity)
    {
        if (is_null($quantity)) {
            throw new \InvalidArgumentException('non-nullable quantity cannot be null');
        }
        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets price
     *
     * @return \OpenAPI\Client\Model\CartMoney|null
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param \OpenAPI\Client\Model\CartMoney|null $price price
     *
     * @return self
     */
    public function setPrice($price)
    {
        if (is_null($price)) {
            throw new \InvalidArgumentException('non-nullable price cannot be null');
        }
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets list_price
     *
     * @return \OpenAPI\Client\Model\CartMoney|null
     */
    public function getListPrice()
    {
        return $this->container['list_price'];
    }

    /**
     * Sets list_price
     *
     * @param \OpenAPI\Client\Model\CartMoney|null $list_price list_price
     *
     * @return self
     */
    public function setListPrice($list_price)
    {
        if (is_null($list_price)) {
            throw new \InvalidArgumentException('non-nullable list_price cannot be null');
        }
        $this->container['list_price'] = $list_price;

        return $this;
    }

    /**
     * Gets discount
     *
     * @return \OpenAPI\Client\Model\CartMoney|null
     */
    public function getDiscount()
    {
        return $this->container['discount'];
    }

    /**
     * Sets discount
     *
     * @param \OpenAPI\Client\Model\CartMoney|null $discount discount
     *
     * @return self
     */
    public function setDiscount($discount)
    {
        if (is_null($discount)) {
            throw new \InvalidArgumentException('non-nullable discount cannot be null');
        }
        $this->container['discount'] = $discount;

        return $this;
    }

    /**
     * Gets base_price
     *
     * @return \OpenAPI\Client\Model\CartMoney|null
     */
    public function getBasePrice()
    {
        return $this->container['base_price'];
    }

    /**
     * Sets base_price
     *
     * @param \OpenAPI\Client\Model\CartMoney|null $base_price base_price
     *
     * @return self
     */
    public function setBasePrice($base_price)
    {
        if (is_null($base_price)) {
            throw new \InvalidArgumentException('non-nullable base_price cannot be null');
        }
        $this->container['base_price'] = $base_price;

        return $this;
    }

    /**
     * Gets custom_price
     *
     * @return \OpenAPI\Client\Model\CartItemCustomPrice|null
     */
    public function getCustomPrice()
    {
        return $this->container['custom_price'];
    }

    /**
     * Sets custom_price
     *
     * @param \OpenAPI\Client\Model\CartItemCustomPrice|null $custom_price custom_price
     *
     * @return self
     */
    public function setCustomPrice($custom_price)
    {
        if (is_null($custom_price)) {
            throw new \InvalidArgumentException('non-nullable custom_price cannot be null');
        }
        $this->container['custom_price'] = $custom_price;

        return $this;
    }

    /**
     * Gets vat_amount
     *
     * @return \OpenAPI\Client\Model\CartMoney|null
     */
    public function getVatAmount()
    {
        return $this->container['vat_amount'];
    }

    /**
     * Sets vat_amount
     *
     * @param \OpenAPI\Client\Model\CartMoney|null $vat_amount vat_amount
     *
     * @return self
     */
    public function setVatAmount($vat_amount)
    {
        if (is_null($vat_amount)) {
            throw new \InvalidArgumentException('non-nullable vat_amount cannot be null');
        }
        $this->container['vat_amount'] = $vat_amount;

        return $this;
    }

    /**
     * Gets vat_percentage
     *
     * @return float|null
     */
    public function getVatPercentage()
    {
        return $this->container['vat_percentage'];
    }

    /**
     * Sets vat_percentage
     *
     * @param float|null $vat_percentage vat_percentage
     *
     * @return self
     */
    public function setVatPercentage($vat_percentage)
    {
        if (is_null($vat_percentage)) {
            throw new \InvalidArgumentException('non-nullable vat_percentage cannot be null');
        }
        $this->container['vat_percentage'] = $vat_percentage;

        return $this;
    }

    /**
     * Gets vat_inaccurate
     *
     * @return bool|null
     */
    public function getVatInaccurate()
    {
        return $this->container['vat_inaccurate'];
    }

    /**
     * Sets vat_inaccurate
     *
     * @param bool|null $vat_inaccurate vat_inaccurate
     *
     * @return self
     */
    public function setVatInaccurate($vat_inaccurate)
    {
        if (is_null($vat_inaccurate)) {
            throw new \InvalidArgumentException('non-nullable vat_inaccurate cannot be null');
        }
        $this->container['vat_inaccurate'] = $vat_inaccurate;

        return $this;
    }

    /**
     * Gets vat_calculated
     *
     * @return bool|null
     */
    public function getVatCalculated()
    {
        return $this->container['vat_calculated'];
    }

    /**
     * Sets vat_calculated
     *
     * @param bool|null $vat_calculated vat_calculated
     *
     * @return self
     */
    public function setVatCalculated($vat_calculated)
    {
        if (is_null($vat_calculated)) {
            throw new \InvalidArgumentException('non-nullable vat_calculated cannot be null');
        }
        $this->container['vat_calculated'] = $vat_calculated;

        return $this;
    }

    /**
     * Gets localized_name
     *
     * @return array<string,string>|null
     */
    public function getLocalizedName()
    {
        return $this->container['localized_name'];
    }

    /**
     * Sets localized_name
     *
     * @param array<string,string>|null $localized_name localized_name
     *
     * @return self
     */
    public function setLocalizedName($localized_name)
    {
        if (is_null($localized_name)) {
            throw new \InvalidArgumentException('non-nullable localized_name cannot be null');
        }
        $this->container['localized_name'] = $localized_name;

        return $this;
    }

    /**
     * Gets product_code
     *
     * @return string|null
     */
    public function getProductCode()
    {
        return $this->container['product_code'];
    }

    /**
     * Sets product_code
     *
     * @param string|null $product_code product_code
     *
     * @return self
     */
    public function setProductCode($product_code)
    {
        if (is_null($product_code)) {
            throw new \InvalidArgumentException('non-nullable product_code cannot be null');
        }
        $this->container['product_code'] = $product_code;

        return $this;
    }

    /**
     * Gets product_sku
     *
     * @return string|null
     */
    public function getProductSku()
    {
        return $this->container['product_sku'];
    }

    /**
     * Sets product_sku
     *
     * @param string|null $product_sku product_sku
     *
     * @return self
     */
    public function setProductSku($product_sku)
    {
        if (is_null($product_sku)) {
            throw new \InvalidArgumentException('non-nullable product_sku cannot be null');
        }
        $this->container['product_sku'] = $product_sku;

        return $this;
    }

    /**
     * Gets image_grn
     *
     * @return string|null
     */
    public function getImageGrn()
    {
        return $this->container['image_grn'];
    }

    /**
     * Sets image_grn
     *
     * @param string|null $image_grn image_grn
     *
     * @return self
     */
    public function setImageGrn($image_grn)
    {
        if (is_null($image_grn)) {
            throw new \InvalidArgumentException('non-nullable image_grn cannot be null');
        }
        $this->container['image_grn'] = $image_grn;

        return $this;
    }

    /**
     * Gets variant_options
     *
     * @return string|null
     */
    public function getVariantOptions()
    {
        return $this->container['variant_options'];
    }

    /**
     * Sets variant_options
     *
     * @param string|null $variant_options variant_options
     *
     * @return self
     */
    public function setVariantOptions($variant_options)
    {
        if (is_null($variant_options)) {
            throw new \InvalidArgumentException('non-nullable variant_options cannot be null');
        }
        $this->container['variant_options'] = $variant_options;

        return $this;
    }

    /**
     * Gets is_virtual
     *
     * @return bool|null
     */
    public function getIsVirtual()
    {
        return $this->container['is_virtual'];
    }

    /**
     * Sets is_virtual
     *
     * @param bool|null $is_virtual is_virtual
     *
     * @return self
     */
    public function setIsVirtual($is_virtual)
    {
        if (is_null($is_virtual)) {
            throw new \InvalidArgumentException('non-nullable is_virtual cannot be null');
        }
        $this->container['is_virtual'] = $is_virtual;

        return $this;
    }

    /**
     * Gets promotion_grns
     *
     * @return string[]|null
     */
    public function getPromotionGrns()
    {
        return $this->container['promotion_grns'];
    }

    /**
     * Sets promotion_grns
     *
     * @param string[]|null $promotion_grns promotion_grns
     *
     * @return self
     */
    public function setPromotionGrns($promotion_grns)
    {
        if (is_null($promotion_grns)) {
            throw new \InvalidArgumentException('non-nullable promotion_grns cannot be null');
        }
        $this->container['promotion_grns'] = $promotion_grns;

        return $this;
    }

    /**
     * Gets additional_info
     *
     * @return string|null
     */
    public function getAdditionalInfo()
    {
        return $this->container['additional_info'];
    }

    /**
     * Sets additional_info
     *
     * @param string|null $additional_info additional_info
     *
     * @return self
     */
    public function setAdditionalInfo($additional_info)
    {
        if (is_null($additional_info)) {
            throw new \InvalidArgumentException('non-nullable additional_info cannot be null');
        }
        $this->container['additional_info'] = $additional_info;

        return $this;
    }

    /**
     * Gets product_data
     *
     * @return string|null
     */
    public function getProductData()
    {
        return $this->container['product_data'];
    }

    /**
     * Sets product_data
     *
     * @param string|null $product_data product_data
     *
     * @return self
     */
    public function setProductData($product_data)
    {
        if (is_null($product_data)) {
            throw new \InvalidArgumentException('non-nullable product_data cannot be null');
        }
        $this->container['product_data'] = $product_data;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    public static function withAdditionalProperties(): bool
    {
        return self::$withAdditionalProperties;
    }


    public function setAdditionalProperty($name, $value)
    {
        throw new \InvalidArgumentException(
            sprintf(
                "This model cannot have additional properties"
            )
        );
    }

    public function getAdditionalProperty($name)
    {
        return $this->additionalProperties[$name];
    }

    public function hasAdditionalProperty($name): bool
    {
        return array_key_exists($name, $this->additionalProperties);
    }

    public function getAdditionalProperties()
    {
        return $this->additionalProperties;
    }
}


