<?php
/**
 * ListCartsRequestFilter
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ListCartsRequestFilter Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ListCartsRequestFilter implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    protected static $withAdditionalProperties = false;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ListCartsRequestFilter';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'search_terms' => 'string[]',
        'customer_emails' => 'string[]',
        'customer_firstnames' => 'string[]',
        'customer_lastnames' => 'string[]',
        'customer_phones' => 'string[]',
        'cart_ids' => 'string[]',
        'cart_status' => '\OpenAPI\Client\Model\ListCartsRequestFilterCartStatus',
        'created_at' => '\OpenAPI\Client\Model\ListCartsRequestFilterDate[]',
        'agent_grn' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'search_terms' => null,
        'customer_emails' => null,
        'customer_firstnames' => null,
        'customer_lastnames' => null,
        'customer_phones' => null,
        'cart_ids' => null,
        'cart_status' => null,
        'created_at' => null,
        'agent_grn' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'search_terms' => false,
        'customer_emails' => false,
        'customer_firstnames' => false,
        'customer_lastnames' => false,
        'customer_phones' => false,
        'cart_ids' => false,
        'cart_status' => false,
        'created_at' => false,
        'agent_grn' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'search_terms' => 'searchTerms',
        'customer_emails' => 'customerEmails',
        'customer_firstnames' => 'customerFirstnames',
        'customer_lastnames' => 'customerLastnames',
        'customer_phones' => 'customerPhones',
        'cart_ids' => 'cartIds',
        'cart_status' => 'cartStatus',
        'created_at' => 'createdAt',
        'agent_grn' => 'agentGrn'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'search_terms' => 'setSearchTerms',
        'customer_emails' => 'setCustomerEmails',
        'customer_firstnames' => 'setCustomerFirstnames',
        'customer_lastnames' => 'setCustomerLastnames',
        'customer_phones' => 'setCustomerPhones',
        'cart_ids' => 'setCartIds',
        'cart_status' => 'setCartStatus',
        'created_at' => 'setCreatedAt',
        'agent_grn' => 'setAgentGrn'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'search_terms' => 'getSearchTerms',
        'customer_emails' => 'getCustomerEmails',
        'customer_firstnames' => 'getCustomerFirstnames',
        'customer_lastnames' => 'getCustomerLastnames',
        'customer_phones' => 'getCustomerPhones',
        'cart_ids' => 'getCartIds',
        'cart_status' => 'getCartStatus',
        'created_at' => 'getCreatedAt',
        'agent_grn' => 'getAgentGrn'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Associative array for storing additional properties
     *
     * @var mixed[]
     */
    protected $additionalProperties = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('search_terms', $data ?? [], null);
        $this->setIfExists('customer_emails', $data ?? [], null);
        $this->setIfExists('customer_firstnames', $data ?? [], null);
        $this->setIfExists('customer_lastnames', $data ?? [], null);
        $this->setIfExists('customer_phones', $data ?? [], null);
        $this->setIfExists('cart_ids', $data ?? [], null);
        $this->setIfExists('cart_status', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('agent_grn', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets search_terms
     *
     * @return string[]|null
     */
    public function getSearchTerms()
    {
        return $this->container['search_terms'];
    }

    /**
     * Sets search_terms
     *
     * @param string[]|null $search_terms search_terms
     *
     * @return self
     */
    public function setSearchTerms($search_terms)
    {
        if (is_null($search_terms)) {
            throw new \InvalidArgumentException('non-nullable search_terms cannot be null');
        }
        $this->container['search_terms'] = $search_terms;

        return $this;
    }

    /**
     * Gets customer_emails
     *
     * @return string[]|null
     */
    public function getCustomerEmails()
    {
        return $this->container['customer_emails'];
    }

    /**
     * Sets customer_emails
     *
     * @param string[]|null $customer_emails customer_emails
     *
     * @return self
     */
    public function setCustomerEmails($customer_emails)
    {
        if (is_null($customer_emails)) {
            throw new \InvalidArgumentException('non-nullable customer_emails cannot be null');
        }
        $this->container['customer_emails'] = $customer_emails;

        return $this;
    }

    /**
     * Gets customer_firstnames
     *
     * @return string[]|null
     */
    public function getCustomerFirstnames()
    {
        return $this->container['customer_firstnames'];
    }

    /**
     * Sets customer_firstnames
     *
     * @param string[]|null $customer_firstnames customer_firstnames
     *
     * @return self
     */
    public function setCustomerFirstnames($customer_firstnames)
    {
        if (is_null($customer_firstnames)) {
            throw new \InvalidArgumentException('non-nullable customer_firstnames cannot be null');
        }
        $this->container['customer_firstnames'] = $customer_firstnames;

        return $this;
    }

    /**
     * Gets customer_lastnames
     *
     * @return string[]|null
     */
    public function getCustomerLastnames()
    {
        return $this->container['customer_lastnames'];
    }

    /**
     * Sets customer_lastnames
     *
     * @param string[]|null $customer_lastnames customer_lastnames
     *
     * @return self
     */
    public function setCustomerLastnames($customer_lastnames)
    {
        if (is_null($customer_lastnames)) {
            throw new \InvalidArgumentException('non-nullable customer_lastnames cannot be null');
        }
        $this->container['customer_lastnames'] = $customer_lastnames;

        return $this;
    }

    /**
     * Gets customer_phones
     *
     * @return string[]|null
     */
    public function getCustomerPhones()
    {
        return $this->container['customer_phones'];
    }

    /**
     * Sets customer_phones
     *
     * @param string[]|null $customer_phones customer_phones
     *
     * @return self
     */
    public function setCustomerPhones($customer_phones)
    {
        if (is_null($customer_phones)) {
            throw new \InvalidArgumentException('non-nullable customer_phones cannot be null');
        }
        $this->container['customer_phones'] = $customer_phones;

        return $this;
    }

    /**
     * Gets cart_ids
     *
     * @return string[]|null
     */
    public function getCartIds()
    {
        return $this->container['cart_ids'];
    }

    /**
     * Sets cart_ids
     *
     * @param string[]|null $cart_ids cart_ids
     *
     * @return self
     */
    public function setCartIds($cart_ids)
    {
        if (is_null($cart_ids)) {
            throw new \InvalidArgumentException('non-nullable cart_ids cannot be null');
        }
        $this->container['cart_ids'] = $cart_ids;

        return $this;
    }

    /**
     * Gets cart_status
     *
     * @return \OpenAPI\Client\Model\ListCartsRequestFilterCartStatus|null
     */
    public function getCartStatus()
    {
        return $this->container['cart_status'];
    }

    /**
     * Sets cart_status
     *
     * @param \OpenAPI\Client\Model\ListCartsRequestFilterCartStatus|null $cart_status cart_status
     *
     * @return self
     */
    public function setCartStatus($cart_status)
    {
        if (is_null($cart_status)) {
            throw new \InvalidArgumentException('non-nullable cart_status cannot be null');
        }
        $this->container['cart_status'] = $cart_status;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \OpenAPI\Client\Model\ListCartsRequestFilterDate[]|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \OpenAPI\Client\Model\ListCartsRequestFilterDate[]|null $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets agent_grn
     *
     * @return string|null
     */
    public function getAgentGrn()
    {
        return $this->container['agent_grn'];
    }

    /**
     * Sets agent_grn
     *
     * @param string|null $agent_grn agent_grn
     *
     * @return self
     */
    public function setAgentGrn($agent_grn)
    {
        if (is_null($agent_grn)) {
            throw new \InvalidArgumentException('non-nullable agent_grn cannot be null');
        }
        $this->container['agent_grn'] = $agent_grn;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    public static function withAdditionalProperties(): bool
    {
        return self::$withAdditionalProperties;
    }


    public function setAdditionalProperty($name, $value)
    {
        throw new \InvalidArgumentException(
            sprintf(
                "This model cannot have additional properties"
            )
        );
    }

    public function getAdditionalProperty($name)
    {
        return $this->additionalProperties[$name];
    }

    public function hasAdditionalProperty($name): bool
    {
        return array_key_exists($name, $this->additionalProperties);
    }

    public function getAdditionalProperties()
    {
        return $this->additionalProperties;
    }
}


