<?php
/**
 * CartSetCustomPriceOnItemsRequestCartItemTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  GeminiCommerce\Cart
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace GeminiCommerce\Cart\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CartSetCustomPriceOnItemsRequestCartItemTest Class Doc Comment
 *
 * @category    Class
 * @description CartSetCustomPriceOnItemsRequestCartItem
 * @package     GeminiCommerce\Cart
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CartSetCustomPriceOnItemsRequestCartItemTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CartSetCustomPriceOnItemsRequestCartItem"
     */
    public function testCartSetCustomPriceOnItemsRequestCartItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "free_of_charge"
     */
    public function testPropertyFreeOfCharge()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "unset"
     */
    public function testPropertyUnset()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "custom_price_row"
     */
    public function testPropertyCustomPriceRow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "custom_price_unit"
     */
    public function testPropertyCustomPriceUnit()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "discount_percentage"
     */
    public function testPropertyDiscountPercentage()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
