<?php
/**
 * BasicOperationsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  GeminiCommerce\Cart
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace GeminiCommerce\Cart\Test\Api;

use \GeminiCommerce\Cart\Configuration;
use \GeminiCommerce\Cart\ApiException;
use \GeminiCommerce\Cart\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BasicOperationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  GeminiCommerce\Cart
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BasicOperationsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addProducts
     *
     * Add Products.
     *
     */
    public function testAddProducts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createCart
     *
     * Create Cart.
     *
     */
    public function testCreateCart()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getActiveCartByCustomer
     *
     * Get Active Cart By Customer.
     *
     */
    public function testGetActiveCartByCustomer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCart
     *
     * Get Cart.
     *
     */
    public function testGetCart()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listCarts
     *
     * List Carts.
     *
     */
    public function testListCarts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mergeCarts
     *
     * Merge Carts.
     *
     */
    public function testMergeCarts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removeProducts
     *
     * Remove Products.
     *
     */
    public function testRemoveProducts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setAdditionalInfo
     *
     * Set Additional Info.
     *
     */
    public function testSetAdditionalInfo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setNotes
     *
     * Set Notes.
     *
     */
    public function testSetNotes()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for triggerRealignment
     *
     * Trigger Realignment.
     *
     */
    public function testTriggerRealignment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateCart
     *
     * Update Cart.
     *
     */
    public function testUpdateCart()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateProducts
     *
     * Update Products.
     *
     */
    public function testUpdateProducts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
